// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Video struct {
	VideoID     string
	Title       sql.NullString
	Thumbnail   sql.NullString
	ChannelName sql.NullString
	Description sql.NullString
	PublishedAt sql.NullString
	Hours       sql.NullInt64
	Minutes     sql.NullInt64
	Seconds     sql.NullInt64
	WasLive     sql.NullInt64
}
